name: fasttake
description: fasttake allows you to take notes instantly the moment they come up on your mind.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite:
  path:

  flutter_datetime_picker: ^1.3.5
  flutter_vector_icons: ^0.2.1
  page_transition: ^1.1.5
  package_info: ^0.4.0+16
  zefyr: ^0.10.0
  local_auth: ^0.6.1+3
  share: ^0.6.3+6
  file_picker: ^1.5.1
  flutter_translate: ^1.5.7
  platform_action_sheet: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/JosefinSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/JosefinSans-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/JosefinSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/JosefinSans-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/JosefinSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/JosefinSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/JosefinSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/JosefinSans-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/JosefinSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/JosefinSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/JosefinSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/JosefinSans-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/JosefinSans-BoldItalic.ttf
          style: italic
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/i18n/

  
        
       
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
